src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    public function __construct(){
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->com = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=0, max=10)
     */
    private $note;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=1, max=200)
     */
    private $nbPlace;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=100, max=10000)
     */
    private $price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $availability;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $phoneNb;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $pieces;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(min=0, max=100)
     */
    private $reduction;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="property", orphanRemoval=true)
     */
    private $comments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(){
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nbPlace;
    }

    public function setNbPlace(int $nbPlace): self
    {
        $this->nbPlace = $nbPlace;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(){
        return number_format($this->price,0,'','');
    }

    public function getAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(bool $availability): self
    {
        $this->availability = $availability;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPhoneNb(): ?int
    {
        return $this->phoneNb;
    }

    public function setPhoneNb(int $phoneNb): self
    {
        $this->phoneNb = $phoneNb;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPieces(): ?int
    {
        return $this->pieces;
    }

    public function setPieces(int $pieces): self
    {
        $this->pieces = $pieces;

        return $this;
    }

    public function getReduction(): ?int
    {
        return $this->reduction;
    }

    public function setReduction(?int $reduction): self
    {
        $this->reduction = $reduction;

        return $this;
    }

    public function getOptions(){
        return $this->options;
    }

    public function addOption(Option $option){
        if(!$this->options->contains($option)){
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option){
        if($this->options->contains($option)){
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Property
     */
    public function setFilename(?string $filename)
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile)
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProperty($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getProperty() === $this) {
                $comment->setProperty(null);
            }
        }

        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, ['label' => 'Titre'])
            ->add('description')
            ->add('size', null, ['label' => 'Surface'])
            ->add('nbPlace', null, ['label' => 'Nombre de place'])
            ->add('city', null, ['label' => 'Ville'])
            ->add('adress', null, ['label' => 'Adresse'])
            ->add('price', null, ['label' => 'Prix'])
            ->add('availability', null, ['label' => 'Disponibilité'])
            ->add('phoneNb', null, ['label' => 'Numéro de téléphone du locataire'])
            ->add('surface')
            ->add('pieces')
            ->add('reduction')
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Commentaires;
use App\Entity\Comments;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\CommentsType;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use function Symfony\Component\Translation\t;

class PropertyController extends AbstractController {

    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em){

        $this->repository = $repository;
        $this->em = $em;

    }

    /**
     * @Route("/appartements", name="properties")
     */
    public function index(PaginatorInterface $paginator, Request $request){

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties =  $paginator->paginate($this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
        15);
        return $this->render('property/index.html.twig', ['current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/appartements/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request){

        $comment = new Comments();

        $commentForm = $this->createForm(CommentsType::class, $comment);

        $commentForm->handleRequest($request);

        if($commentForm->isSubmitted() && $commentForm->isValid()){

            if(!$this->isGranted('IS_AUTHENTICATED_FULLY')){

                $this->addFlash('warning','Veuillez vous connecter avant de poster un message.');
                return $this->render('property/show.html.twig', [
                    'property' => $property,
                    'current_menu' => 'properties',
                    'commentForm' => $commentForm->createView()
                ]);

            }

            $comment->setCreatedAt(new \DateTime());
            $comment->setProperty($property);

            $parentid = $commentForm->get("parentid")->getData();

            $em = $this->getDoctrine()->getManager();

            if ($parentid != null){
                $parent = $em->getRepository(Comments::class)->find($parentid);
            }

            $comment->setParent($parent ?? null);

            $em->persist($comment);
            $em->flush();

            $this->addFlash('message', 'Votre commentaire a bien été envoyé');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }


        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'commentForm' => $commentForm->createView()
        ]);
    }

}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% else %}
        <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text">{{ property.surface }} en m² - {{ property.city }} | {{ property.adress }}</p>
        <div class="text-primary" style="font-size:2rem; font-weight: bold;">
            {{ property.formattedPrice }} €
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Appartements et chalets | Agence TropDeChalet'%}

{% block body %}

    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="row align-items-end">
                    <div class="col">
                        {{ form_row(form.minSurface) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.maxPrice) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.options) }}
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <button class="btn btn-primary">Rechercher</button>
                        </div>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Voir toutes les offres</h1>

        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}

    {% for message in app.flashes('warning') %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
    {% endfor %}


    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% else %}
                        <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.nbplace }} personnes habitables</h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice }} € la nuit</div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">

        <p>
             {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2>Informations</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Nombre de personnes habitables</td>
                        <td>{{ property.nbplace }}</td>
                    </tr>
                    <tr>
                        <td>Reduction</td>
                        <td>{{ property.reduction }}</td>
                    </tr>
                    <tr>
                        <td>Surface totale en m²</td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td>Numero de telephone du gérant</td>
                        <td>+32 {{ property.phoneNb }}</td>
                    </tr>
                    <tr>
                        <td>Nombres de pièces</td>
                        <td>{{ property.pieces }}</td>
                    </tr>
                    <tr>
                        <td>Note de l'agence</td>
                        <td>{{ property.note }} / 10</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Options supplémentaires</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                    <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-md-8">

                <hr/>

                <h2>Liste des commentaires</h2>
                {% for comment in property.comments %}

                    {% if comment.parent == null %}

                        <h4> Commentaire de {{ comment.nickname }}</h4>

                        <p>Publié le {{ comment.createdAt|date("d/m/Y H:i") }}</p>
                        <div>{{ comment.content }}</div>
                        <p>
                            <a href="#ajout-commentaire" data-reply data-id="{{ comment.id }}" type="button" class="btn btn-primary">Répondre</a>
                        </p>

                    {% endif %}

                    {% for reply in comment.replies %}

                        <h6>Réponse publiée par {{ reply.nickname }} le {{ reply.createdAt|date("d/m/Y H:i") }}</h6>
                        <p></p>
                        <div>{{ reply.content }}</div>

                    {% endfor %}

                {% endfor %}

                <hr/>

                <div id="ajout-commentaire"></div>
                <h2>Ajouter un commentaire</h2>
                {{ form(commentForm) }}

            </div>
        </div>
    </div>


{% endblock %}

{% block javascripts %}

    <script>
        window.onload = () => {

            document.querySelectorAll("[data-reply]").forEach(element => {
                element.addEventListener("click", function(){
                    document.querySelector("#comments_parentid").value = this.dataset.id;
                });
            });

        }
    </script>

{% endblock %}